---
# install_ntp/tasks/main.yml

- name: 'Install ntp'
  package:
    name: "{{ ntp_package }}"
    state: 'present'
  when: >
    ((ansible_distribution == "SLES" or ansible_distribution == "openSUSE Leap" or ansible_distribution == "openSUSE MicroOS")
    and ansible_distribution_major_version|int < 15)
    or
    ((ansible_distribution == "CentOS" or ansible_distribution == "RedHat") and ansible_distribution_major_version|int < 8)
    or
    ansible_os_family == "debian"
