---
# install_ntp/tasks/main.yml

- name: 'Install ntp'
  package:
    name: "{{ ntp_package }}"
    state: 'present'
  when:
    - '
      (ansible_os_family == "Suse" and ansible_distribution_major_version|int < 15)
      or
      (ansible_os_family == "RedHat" and ansible_distribution_major_version|int < 8)
      or
      ansible_os_family == "debian"
      '
